export type Question = {
  id: number;
  text: string;
  choices: [string, string, string, string];
  correctAnswerIndex: number;
  correctAnswerPoints: number;
};

export const QUESTIONS_BY_TILE_INDEX: Record<number, Question> = {
  1: {
    id: 1,
    text: "A scientist uses a computer simulation to show how air behaves inside a syringe. Why is the simulation considered a model?",
    choices: [
      " It represents things that are too small to see directly",
      "It removes the need to perform real experiments.",
      "It is a perfect physical copy of air.",
      "It is used when scientists do not have facts.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 1,
  },
  3: {
    id: 2,
    text: " Which statement best explains the basic composition of all matter?",
    choices: [
      " Matter is one solid continuous material.",
      " Matter is made up of tiny particles.",
      "Matter is made of visible tiny bubbles.",
      "Matter is formed from pure energy waves.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 1,
  },
  6: {
    id: 3,
    text: "In the Particle Model of Matter, what is present in the empty spaces between two gas particles?",
    choices: [" Air.", " Dust.", "Nothing.", "Heat energy."],
    correctAnswerIndex: 2,
    correctAnswerPoints: 1,
  },
  8: {
    id: 4,
    text: "Which state of matter has particles that only vibrate while staying in fixed positions?",
    choices: [" Gas.", " Liquid.", "Plasma.", "Solid."],
    correctAnswerIndex: 3,
    correctAnswerPoints: 1,
  },
  12: {
    id: 5,
    text: "When a pure substance changes from solid to liquid, what happens to the kind of particles it has?",
    choices: [
      "They remain the same kind of particles.",
      "They change into another kind of particle.",
      "They disappear and turn into heat.",
      "They become particles found only in liquids.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 1,
  },
  16: {
    id: 6,
    text: " Which tool would best help a scientist explain a phenomenon that cannot be easily observed?",
    choices: [
      "A camera.",
      "A scientific model.",
      "A magnifying glass.",
      "A detailed textbook.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 1,
  },
  21: {
    id: 7,
    text: "How are the particles of two different pure substances, such as pure water and pure sugar, related to each other?",
    choices: [
      " They are exactly the same kind.",
      "They differ only in color.",
      "They are different kinds of particles.",
      "They differ only in total weight.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 1,
  },
  25: {
    id: 8,
    text: "Which state of matter has particles that are widely spaced and move randomly in all directions?",
    choices: ["Rock.", " Solid.", " Liquid.", "Gas."],
    correctAnswerIndex: 3,
    correctAnswerPoints: 1,
  },
  31: {
    id: 9,
    text: " Which description best shows how particles behave in a liquid?",
    choices: [
      " They are close together but can move past one another.",
      "  They are tightly locked in a regular pattern.",
      "They travel very fast in straight paths.",
      " They are separated by very large spaces.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 1,
  },
  34: {
    id: 10,
    text: "When a substance expands after being heated, what happens to the number of particles in it?",
    choices: [
      "It becomes twice as many.",
      "It remains the same.",
      "It increases a little because of heat.",
      "It decreases when melting begins.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 1,
  },
  36: {
    id: 11,
    text: "Why can air inside a syringe be compressed easily, while liquid water cannot be compressed easily?",
    choices: [
      "Air is lighter than water.",
      "Water is a liquid substance.",
      "Gas particles have larger spaces between them.",
      "Air particles are softer than water particles.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 2,
  },
  39: {
    id: 12,
    text: "Why does a drop of ink spread throughout a glass of still water even without stirring?",
    choices: [
      " The water naturally wants to change color.",
      " Gravity continuously pulls the ink downward.",
      " The ink particles are heavier than water particles.",
      " The particles are always moving randomly.",
    ],
    correctAnswerIndex: 3,
    correctAnswerPoints: 2,
  },
  43: {
    id: 13,
    text: "Why does a liquid take the shape of its container, while a solid keeps its own shape?",
    choices: [
      "Liquid particles can slide past one another.",
      "Solids are naturally heavier than liquids.",
      "Solids have no particles on their surface.",
      "Liquid particles move faster than gas particles.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 2,
  },
  45: {
    id: 14,
    text: " A tightly tied balloon becomes smaller after several days. What is the best scientific explanation for this observation?",
    choices: [
      "The air inside the balloon died.",
      "Air particles passed through tiny pores.",
      "The air inside simply became colder.",
      "The particles became smaller in size.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 2,
  },
  47: {
    id: 15,
    text: " What causes gas pressure inside a bicycle tire?",
    choices: [
      "The particles are very heavy.",
      "The air inside is becoming very hot.",
      "Particles continuously hit the inner walls of the tire.",
      "Particles rest heavily against the rubber walls.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 2,
  },
  50: {
    id: 16,
    text: "Why do scientists use different models, such as drawings and 3D balls, to explain the same scientific idea?",
    choices: [
      "One model is always wrong.",
      "Models are only useful for young learners.",
      "Scientists can never agree on the facts.",
      "Each model shows a different important feature.",
    ],
    correctAnswerIndex: 3,
    correctAnswerPoints: 2,
  },
  53: {
    id: 17,
    text: "When liquid water boils and becomes steam, what happens to the spaces between its particles?",
    choices: [
      "The spaces become much larger.",
      "The spaces remain exactly the same.",
      "The spaces become slightly smaller.",
      "The spaces disappear as particles turn into heat.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 2,
  },
  58: {
    id: 18,
    text: "Why can an educational board game be a useful model for learning the states of matter?",
    choices: [
      "It is used only for entertainment.",
      "It helps learners picture abstract particle behavior.",
      "It removes the need for science experiments.",
      "It looks exactly like real particles under a microscope.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 2,
  },
  60: {
    id: 19,
    text: "How does the Particle Model explain why solids do not flow like liquids?",
    choices: [
      "Solid objects do not contain particles.",
      "Solid particles have no energy at all.",
      "Strong attractions hold the particles in place.",
      "Solid particles are too large to move freely.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 2,
  },
  65: {
    id: 20,
    text: " Why can the smell of food cooking in the kitchen reach you even if you are in another room?",
    choices: [
      "The air in the room is very cold.",
      "Your nose pulls the smell toward you.",
      "The house is small enough for the smell to move around.",
      "Gas particles move randomly and mix with the surrounding air.",
    ],
    correctAnswerIndex: 3,
    correctAnswerPoints: 2,
  },
  70: {
    id: 21,
    text: "A student says that particles in ice stop moving completely because ice is frozen. How should this idea be corrected?",
    choices: [
      "The particles still vibrate in fixed positions.",
      "The particles turn into liquid water.",
      "The particles become larger because of the cold.",
      "The particles move faster when they are frozen.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 3,
  },

  75: {
    id: 22,
    text: "A metal bolt is heated and no longer fits into its nut. What happened to the particles of the bolt?",
    choices: [
      "They became physically larger.",
      "They moved farther apart after gaining energy.",
      "They increased rapidly in number.",
      "They became much heavier because of heat.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 3,
  },
  79: {
    id: 23,
    text: "A sealed jar contains pure oxygen. If half of the oxygen particles are removed, what remains inside the jar?",
    choices: [
      "Pure heat.",
      "Half oxygen and half regular air.",
      "Fewer oxygen particles with more empty space.",
      "A completely empty vacuum.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 3,
  },
  83: {
    id: 24,
    text: "A computer simulation shows particles packed close together but arranged randomly. Which state of matter is represented?",
    choices: ["Gas.", "Solid.", "Vacuum.", "Liquid."],
    correctAnswerIndex: 3,
    correctAnswerPoints: 3,
  },
  84: {
    id: 25,
    text: " A dented plastic ping-pong ball is placed in hot water, and the dent pops out. Why does this happen?",
    choices: [
      "The air particles inside push the walls outward.",
      "Hot water enters the ball.",
      "The plastic melts quickly.",
      "The ball expands on its own without particle movement.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 3,
  },

  87: {
    id: 26,
    text: "When 50 mL of salt is mixed with 100 mL of water, the total volume becomes less than 150 mL. Why does this happen?",
    choices: [
      "The salt completely melts away.",
      "Salt particles fit into spaces between water particles.",
      "The water quickly evaporates.",
      "Some particles are destroyed during mixing.",
    ],
    correctAnswerIndex: 1,
    correctAnswerPoints: 3,
  },
  90: {
    id: 27,
    text: "On a cold morning, fog forms on the inside of a car window. What is happening to the particles?",
    choices: [
      "The glass is sweating.",
      "New water is being formed.",
      "Gas particles slow down and come together as liquid.",
      "Air particles slowly change into solid glass.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 3,
  },
  92: {
    id: 28,
    text: "Why does a wet floor dry faster when an electric fan blows air over it?",
    choices: [
      "The wind makes liquid particles heavier.",
      "The fan gives strong heat to the wet particles.",
      "The wind produces new water particles.",
      "Moving air helps liquid particles leave the surface faster.",
    ],
    correctAnswerIndex: 3,
    correctAnswerPoints: 3,
  },
  95: {
    id: 29,
    text: " A strong-smelling fruit is placed inside a plastic bag described as smell-proof, but the smell is still noticed later. Why can this happen?",
    choices: [
      "Some particles are small enough to pass through microscopic gaps.",
      "The smell acts like a ghost.",
      "The bag is secretly made of air.",
      "The smell produces its own air to move around.",
    ],
    correctAnswerIndex: 0,
    correctAnswerPoints: 3,
  },
  96: {
    id: 30,
    text: "Which evidence best shows that solid ice and hot steam are made of the same kind of particles?",
    choices: [
      "Both of them feel wet.",
      "Both can become very hot.",
      "Both can change back into liquid water.",
      "Both look like white clouds in the air.",
    ],
    correctAnswerIndex: 2,
    correctAnswerPoints: 3,
  },
};
